version: "{build}"

image: Visual Studio 2019

platform:
  - Any CPU

configuration:
  - Release

build_script:
  - msbuild "src\SubtitleEdit.sln" /r /v:minimal /clp:summary /p:"Platform=%PLATFORM%" /p:"Configuration=%CONFIGURATION%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - vstest.console "src\Test\bin\%CONFIGURATION%\Test.dll" /logger:Appveyor

cache:
  - 'src\packages -> **\packages.config'       # preserve the "src\packages" directory

matrix:
  fast_finish: true
